### ISSUE TITLE
Validation error with file input type

### ISSUE THREAD

**Issue by bdielman** [pixelandtonic/GuestEntries#12] opened 2016-07-26 21:04 UTC
I have a guest entries front-end form which allows users to upload photos. Certain fields, including the file input are required, but when the page reloads after returning a validation error all page elements including and after file select aren't rendered. If I add an image to the file select input prior to triggering a validation error that field is rendered but then it has JS set in the value, breaking all the markup on the page from that point.

This is my first time using the plugin so I'm positive it's something I didn't setup or code correctly. Here's the form code as it is now:

```php
<form action="" method="post" enctype="multipart/form-data" accept-charset="UTF-8">
  {{ getCsrfInput() }}
  {{ craft.sproutInvisibleCaptcha.protect() }}
  <input name="MAX_FILE_SIZE" type="hidden" value="67108864">
  <input type="hidden" name="action" value="guestEntries/saveEntry">
  <input type="hidden" name="redirect" value="/thankyou">
  <input type="hidden" name="sectionId" value="13">
  <input type="hidden" name="typeId" value="13">
  <input type="hidden" name="title" value="Photo Gallery">
  <input type="hidden" name="postDate[date]" value="{{ "now"|date("m/d/Y") }}">
  <input type="hidden" name="postDate[time]" value="{{ "now"|date("h:i:s A") }}">

  {% if guestEntry is defined %}{% if guestEntry.errors|length > 0 %}
    <div class="alert alert-danger">
      <h3>There was a problem with your submission:</h3>
      {% for error in guestEntry.errors %}
      {% for errormessage in error %}
      <p>{{errormessage}}</p>
      {% endfor %}
      {% endfor %}
    </div>
  {% endif %}{% endif %}

  <input required type="text"{% if guestEntry is defined %} value="{{ guestEntry.userFirstName }}"{% endif %} class="form-control" name="fields[userFirstName]" id="input_first_name" placeholder="First Name">
  <input required type="text"{% if guestEntry is defined %} value="{{ guestEntry.userLastName }}"{% endif %} class="form-control" name="fields[userLastName]" id="input_last_name" placeholder="Last Name">
  <input type="text"{% if guestEntry is defined %} value="{{ guestEntry.userTitle }}"{% endif %} class="form-control" name="fields[userTitle]" id="input_title" placeholder="Title">
  <input required type="file"{% if guestEntry is defined %} value="{{ guestEntry.userPhoto }}"{% endif %} class="form-control" name="fields[userPhoto]" id="input_photo" accept="image/*">
  <textarea required name="fields[userQuote]" rows="8" cols="40" placeholder="Add your quote" class="form-control" id="input_quote">{% if guestEntry is defined %}{{ guestEntry.userQuote }}{% endif %}</textarea>
  <input type="text"{% if guestEntry is defined %} value="{{ guestEntry.userFacebookHandle }}"{% endif %} class="form-control" name="fields[userFacebookHandle]" id="input_facebook_handle" placeholder="Add your Facebook handle">
  <input type="text"{% if guestEntry is defined %} value="{{ guestEntry.userInstagramHandle }}"{% endif %} class="form-control" name="fields[userInstagramHandle]" id="input_instagram_handle" placeholder="Add your Instagram handle">
  <input type="text"{% if guestEntry is defined %} value="{{ guestEntry.userTwitterHandle }}"{% endif %} class="form-control" name="fields[userTwitterHandle]" id="input_twitter_handle" placeholder="Add your Twitter handle">

  <button type="submit" class="btn btn-lg btn-primary">Send Request</button>
</form>
```

**Comment by takobell** [comment] 2016-07-26 23:17
I'm not able to reproduce this with similar (but stripped down) form code:

    <form action="" method="post" enctype="multipart/form-data" accept-charset="UTF-8">

        <input type="hidden" name="action" value="guestEntries/saveEntry">
        <input type="hidden" name="redirect" value="/thankyou">
        <input type="hidden" name="sectionId" value="3">
        <input type="hidden" name="typeId" value="3">
        <input type="hidden" name="postDate[date]" value="{{ "now"|date("m/d/Y") }}">
        <input type="hidden" name="postDate[time]" value="{{ "now"|date("h:i:s A") }}">

        {% if entry is defined %}
            {% if entry.errors|length > 0 %}
                <div>
                    <h3>There was a problem with your submission:</h3>
                    {% for error in entry.errors %}
                        {% for errormessage in error %}
                            <p>{{errormessage}}</p>
                        {% endfor %}
                   {% endfor %}
               </div>
           {% endif %}
       {% endif %}

      <input type="text"{% if entry is defined %} value="{{ entry.userFirstName }}"{% endif %} name="fields[userFirstName]" id="input_first_name" placeholder="First Name">
      <input type="text"{% if entry is defined %} value="{{ entry.title }}"{% endif %} name="title" id="title" placeholder="Title">
      <input type="file" class="form-control" name="fields[userPhoto]" id="input_photo" accept="image/*">

      <button type="submit">Send Request</button>
    </form>

Title, userPhoto and userFirstName are all marked as required and I get the proper validation error messages.  I'd start by disabling all plugins (besides Guest Entries) and narrowing down your template/form code to rule out variables.

**Closed by takobell** 2016-07-26 23:17 UTC

**Comment by bdielman** [comment] 2016-07-27 00:30
Thanks Brad!
